### ISSUE TITLE
[BUG] Nav icon as text not removing original

### ISSUE THREAD

**Issue by Rhaedas** [aclist/kbin-kes#156]
When the script to change the search, post, and channel icons is enabled it does replace the channels one, but leaves the original search and post beside the new replacement text. See attached screenshot.

**KES version:**
- Version number [e.g. 2.0.2]

**Extension and version:**
- Extension: ViolentMonkey 2.14

![Capture](https://github.com/aclist/kbin-kes/assets/69368125/0412d62e-623b-4bfe-9c14-794f9a79780e)
 - OS: Windows
 - Browser Firefox

**Comment by aclist** [comment]
This should be fixed in a  patch going out today. We've also changed it so that it respects the browser's font face when rendering the text. (It was reverting to the internal font face used by icons).

**Comment by aclist** [comment]
Resolved by e736e3675d319bb6edd03f220ef5b31c43001bb3

**Comment by Rhaedas** [comment]
Just updated to 2.1.0 and this problem remains on my machine. The font did change with the previous fixes, but the Search and Post text is still duplicated both then (2.0.7?) and now with 2.1.0.

**Comment by aclist** [comment]
I am thinking. How did you update KES? Is there a page on the sidebar called Accessibility with an option inside it called Chane font size? (This is just a test. I am wondering if your script manager did not actually pull in the new resources.)

**Comment by Rhaedas** [comment]
I clicked on the version number in the wrench menu to get to the reinstall page, clicked on that, then refreshed. I see the newer scripts like the font changing one so I think everything updated. I even tried to turn off the feature in question, reset, then turn on again and reset.

**Comment by aclist** [comment]
OK, sounds like you are up to date, just wanted to eliminate possibilities here, since it *should* be working. I will investigate and try to reproduce.

The font weight depends on what fallback font your browser is using and if it supports multiple weights. It may or may not do anything. I think we can probably drop the slider and let the browser handle it.

**Comment by aclist** [comment]
@minnieoo  are you able to reproduce this?

**Comment by minnieoo** [comment]
I don't have this issue. both the mod and the font weight slider work as expected for me. using 2.1.0. Works on both tampermonkey and violentmonkey. I am also on windows and using firefox. 

![image](https://github.com/aclist/kbin-kes/assets/137783738/d8587421-65a1-4ad1-aec9-fc7b8eb8beac)

**Comment by Rhaedas** [comment]
Found the problem. It was an older Stylus CSS I had installed for some things called idkbin that was conflicting.

**Comment by aclist** [comment]
Now that you mention, my [kbin-css](https://github.com/aclist/kbin-css/tree/main) also had logic to insert text there, I should drop that from the CSS so that it complies.
